"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AUTH_SUCCESS = "AUTH_SUCCESS";
exports.AUTH_REG_SUCCESS = "AUTH_REG_SUCCESS";
exports.AUTH_ERROR_CLEAN = "AUTH_ERROR_CLEAN";
exports.AUTH_REGISTERED_CLEAN = "AUTH_REGISTERED_CLEAN";
exports.AUTH_FAILED = "AUTH_FAILED";
exports.REQUEST = "REQUEST";
exports.REQUEST_RESPONSE = "REQUEST_RESPONSE";
exports.ROOM_UPDATE = "ROOM_UPDATE";
exports.PLAYER_UPDATE = "PLAYER_UPDATE";
exports.MONSTER_UPDATE = "MONSTER_UPDATE";
exports.FIELD_CLEAN = "FIELD_CLEAN";
exports.CONTROLLER_UPDATE = "CONTROLLER_UPDATE";
exports.CONTROLLER_CLEAN = "CONTROLLER_CLEAN";
//# sourceMappingURL=actionTypes.js.map