export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_REG_SUCCESS = "AUTH_REG_SUCCESS";
export const AUTH_ERROR_CLEAN = "AUTH_ERROR_CLEAN";
export const AUTH_REGISTERED_CLEAN = "AUTH_REGISTERED_CLEAN";
export const AUTH_FAILED = "AUTH_FAILED";

export const REQUEST = "REQUEST";
export const REQUEST_RESPONSE = "REQUEST_RESPONSE";

export const ROOM_UPDATE = "ROOM_UPDATE";
export const PLAYER_UPDATE = "PLAYER_UPDATE";
export const MONSTER_UPDATE = "MONSTER_UPDATE";
export const FIELD_CLEAN = "FIELD_CLEAN";

export const CONTROLLER_UPDATE = "CONTROLLER_UPDATE";
export const CONTROLLER_CLEAN = "CONTROLLER_CLEAN";
export const CHANGE_LEADERBOARD_MODAL = "CHANGE_LEADERBOARD_MODAL";

export const LOG_UPDATE = "LOG_UPDATE";
export const LOG_CLEAN = "LOG_CLEAN";

export const LEADERBOARD_UPDATE_PAGE = "LEADERBOARD_UPDATE_PAGE";