language: csharp
mono: none
dotnet: 3.0

install:
- dotnet restore

script:
- dotnet build
- dotnet test tests/User.Test/User.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
- dotnet test tests/Room.Test/Room.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
- dotnet test tests/Monster.Test/Monster.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
