language: csharp
mono: none
dotnet: 3.0

install:
- dotnet restore

script:
- dotnet build
- dotnet test User.Test/User.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
- bash <(curl -s https://codecov.io/bash)