// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Room.API.Models;

namespace Room.API.Migrations
{
    [DbContext(typeof(RoomContext))]
    [Migration("20191104230434_DiscovererIdString")]
    partial class DiscovererIdString
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Room.API.Models.RoomModel", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DiscovererId")
                        .HasColumnType("text");

                    b.Property<bool>("EastRoom")
                        .HasColumnType("boolean");

                    b.Property<int?>("EastRoomId")
                        .HasColumnType("integer");

                    b.Property<int?>("MonsterId")
                        .HasColumnType("integer");

                    b.Property<bool>("NorthRoom")
                        .HasColumnType("boolean");

                    b.Property<int?>("NorthRoomId")
                        .HasColumnType("integer");

                    b.Property<bool>("SouthRoom")
                        .HasColumnType("boolean");

                    b.Property<int?>("SouthRoomId")
                        .HasColumnType("integer");

                    b.Property<bool>("Treasure")
                        .HasColumnType("boolean");

                    b.Property<bool>("WestRoom")
                        .HasColumnType("boolean");

                    b.Property<int?>("WestRoomId")
                        .HasColumnType("integer");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
