// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Room.API.Models;

namespace Room.API.Migrations
{
    [DbContext(typeof(RoomContext))]
    [Migration("20191027112846_BoolRoomProperties")]
    partial class BoolRoomProperties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Room.API.Models.RoomModel", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("EastRoom");

                    b.Property<int?>("EastRoomId");

                    b.Property<int?>("MonsterId");

                    b.Property<bool>("NorthRoom");

                    b.Property<int?>("NorthRoomId");

                    b.Property<bool>("SouthRoom");

                    b.Property<int?>("SouthRoomId");

                    b.Property<bool>("Treasure");

                    b.Property<bool>("WestRoom");

                    b.Property<int?>("WestRoomId");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
